general {
    lock_cmd = pidof hyprlock || hyprlock       # prevent multiple instances
    before_sleep_cmd = loginctl lock-session    # lock before device goes to sleep
    after_sleep_cmd = hyprctl dispatch dpms on  # wake up display when waking from sleep
}

# 1. Dim the screen after 3 minutes of inactivity
listener {
    timeout = 180
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# 2. Lock the screen after 5 minutes of inactivity
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 3. Turn off the physical display after 6 minutes
listener {
    timeout = 360
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 4. Hibernate the laptop after 30 minutes of inactivity
listener {
    timeout = 1800                              # 30 mins * 60 secs
    on-timeout = systemctl hibernate            # writes RAM to disk and shuts off power
}
